# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-03 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_album_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='is_favorite',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='is_favorite',
            field=models.BooleanField(default=True),
        ),
    ]
